// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	upload "mallxx_server/upload/api/internal/handler/upload"
	"mallxx_server/upload/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/token",
				Handler: upload.TokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/upload"),
	)
}
