// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	sign "mallxx_server/sign/api/internal/handler/sign"
	"mallxx_server/sign/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: sign.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: sign.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/signout",
				Handler: sign.SignOutHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/verify/token",
				Handler: sign.VerifyTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/sign"),
	)
}
