// Code generated by goctl. DO NOT EDIT!
// Source: advertise.proto

package advertiseservice

import (
	"context"

	"mallxx_server/advertise/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdInfoResponse = pb.AdInfoResponse
	AdOneRequest   = pb.AdOneRequest
	AdRequest      = pb.AdRequest
	AdResponse     = pb.AdResponse
	Advertise      = pb.Advertise
	Response       = pb.Response

	AdvertiseService interface {
		AdminGetList(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*AdResponse, error)
		ApiGetList(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*AdResponse, error)
		GetInfo(ctx context.Context, in *AdOneRequest, opts ...grpc.CallOption) (*AdInfoResponse, error)
		Add(ctx context.Context, in *Advertise, opts ...grpc.CallOption) (*Response, error)
		Delete(ctx context.Context, in *AdOneRequest, opts ...grpc.CallOption) (*Response, error)
		Update(ctx context.Context, in *Advertise, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAdvertiseService struct {
		cli zrpc.Client
	}
)

func NewAdvertiseService(cli zrpc.Client) AdvertiseService {
	return &defaultAdvertiseService{
		cli: cli,
	}
}

func (m *defaultAdvertiseService) AdminGetList(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*AdResponse, error) {
	client := pb.NewAdvertiseServiceClient(m.cli.Conn())
	return client.AdminGetList(ctx, in, opts...)
}

func (m *defaultAdvertiseService) ApiGetList(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*AdResponse, error) {
	client := pb.NewAdvertiseServiceClient(m.cli.Conn())
	return client.ApiGetList(ctx, in, opts...)
}

func (m *defaultAdvertiseService) GetInfo(ctx context.Context, in *AdOneRequest, opts ...grpc.CallOption) (*AdInfoResponse, error) {
	client := pb.NewAdvertiseServiceClient(m.cli.Conn())
	return client.GetInfo(ctx, in, opts...)
}

func (m *defaultAdvertiseService) Add(ctx context.Context, in *Advertise, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewAdvertiseServiceClient(m.cli.Conn())
	return client.Add(ctx, in, opts...)
}

func (m *defaultAdvertiseService) Delete(ctx context.Context, in *AdOneRequest, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewAdvertiseServiceClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}

func (m *defaultAdvertiseService) Update(ctx context.Context, in *Advertise, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewAdvertiseServiceClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}
