// Code generated by goctl. DO NOT EDIT.
package types

type Advertise struct {
	Id         int64  `json:"id,optional" db:"id"`
	Name       string `json:"name" db:"name"`
	Img        string `json:"img" db:"img"`
	Pos        int32  `json:"pos" db:"pos"`
	CategoryId int64  `json:"category_id" db:"category_id"`
	Type       int32  `json:"type" db:"type"`
	Url        string `json:"url" db:"url"`
	GoId       int32  `json:"go_id" db:"go_id"`
	Status     int32  `json:"status" db:"status"`
	StartTime  string `json:"start_time" db:"start_time"`
	EndTime    string `json:"end_time" db:"end_time"`
	AddTime    string `json:"add_time" db:"add_time"`
}

type AdRequest struct {
	Pos        int32  `json:"pos,optional" form:"pos,optional"` //
	CategoryId int64  `json:"category_id,optional" form:"category_id,optional"`
	Status     int32  `json:"status,optional" form:"status,optional"`
	PageSize   int32  `json:"page_size,optional" form:"page_size,optional"`
	PageNum    int32  `json:"page_num,optional" form:"page_num,optional"`
	StartTime  string `json:"start_time,optional" form:"start_time,optional"`
	EndTime    string `json:"end_time,optional" form:"end_time,optional"`
	Name       string `json:"name,optional" form:"name,optional"`
}

type AdOneRequest struct {
	Id int64 `json:"id" form:"id"`
}

type AdResponse struct {
	Code   int32        `json:"code"`
	Data   []*Advertise `json:"data"`
	Total  int64        `json:"total"`
	Detail string       `json:"detail"`
}

type AdInfoResponse struct {
	Code   int32      `json:"code"`
	Data   *Advertise `json:"data"`
	Detail string     `json:"detail"`
}

type Response struct {
	Code   int32  `json:"code"`
	Detail string `json:"detail"`
}
