// Code generated by goctl. DO NOT EDIT.
package types

type ListRequest struct {
	PageNum  int32  `json:"page_num,omitempty" form:"pageNum"`
	PageSize int32  `json:"page_size,omitempty" form:"pageSize"`
	Keyword  string `json:"keyword,omitempty" form:"keyword"`
	Pid      int64  `json:"pid,omitempty" form:"pid"`
}

type Response struct {
	Code   int32  `json:"code,omitempty"`
	Detail string `json:"detail,omitempty"`
}

type EmptyRequest struct {
}

type FollowerResponse struct {
	Code   int32     `json:"code"`
	Data   []*Member `json:"data"`
	Detail string    `json:"detail"`
	Total  int32     `json:"total"`
}

type MemberLevel struct {
	Id                    int64   `json:"id" db:"id"`
	GrowthPoint           int32   `json:"growth_point" db:"growth_point"`
	DefaultStatus         int32   `json:"default_status" db:"default_status"`
	FreeFreightPoint      float32 `json:"free_freight_point" db:"free_freight_point"`
	CommentGrowthPoint    int32   `json:"comment_growth_point" db:"comment_growth_point"`
	PriviledgeFreeFreight int32   `json:"priviledge_free_freight" db:"priviledge_free_freight"`
	PriviledgeSignIn      int32   `json:"priviledge_sign_in" db:"priviledge_sign_in"`
	PriviledgeComment     int32   `json:"priviledge_comment" db:"priviledge_comment"`
	PriviledgePromotion   int32   `json:"priviledge_promotion" db:"priviledge_promotion"`
	PriviledgeMemberPrice int32   `json:"priviledge_member_price" db:"priviledge_member_price"`
	PriviledgeBirthday    int32   `json:"priviledge_birthday" db:"priviledge_birthday"`
	Note                  string  `json:"note" db:"note"`
	Name                  string  `json:"name" db:"name"`
}

type MemverLevelInfoRequest struct {
}

type MemverLeveListResponse struct {
	Code   int32          `json:"code,omitempty"`
	Data   []*MemberLevel `json:"data,omitempty"`
	Detail string         `json:"detail,omitempty"`
}

type Member struct {
	Id          int64  `json:"id,optional"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	Phone       string `json:"phone"`
	Email       string `json:"email"`
	Avatar      string `json:"avatar"`
	Status      int32  `json:"status"`
	AddTime     int64  `json:"add_time"`
	MemberLevel int64  `json:"member_level"`
	Gender      int32  `json:"gender"`
	Birthday    int32  `json:"birthday"`
	Token       string `json:"token" xorm:"-"`
	Integral    int32  `json:"integral"`
	Coupon      int32  `json:"coupon"`
	Followers   int32  `json:"followers"`
	Nickname    string `json:"nickname"`
}

type MemberData struct {
	Member      *Member      `json:"member"`
	MemberLevel *MemberLevel `json:"member_level"`
}

type MemberResponse struct {
	Code   int32       `json:"code"`
	Data   *MemberData `json:"data"`
	Detail string      `json:"detail"`
}

type MemberListResponse struct {
	Code   int32         `json:"code"`
	Data   []*MemberData `json:"data"`
	Detail string        `json:"detail"`
	Total  int32         `json:"total"`
}

type MemberRequest struct {
	Uid int64 `json:"uid" form:"uid"`
}

type MemberLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
}

type ReceiveAddress struct {
	Id            int64  `json:"id,optional"`
	MemberId      int64  `json:"member_id,optional"`
	Phone         string `json:"phone"`
	DefaultStatus int32  `json:"default_status,optional"`
	PostCode      string `json:"post_code,optional"`
	Province      string `json:"province"`
	City          string `json:"city"`
	Region        string `json:"region"`
	Detail        string `json:"detail"`
	Name          string `json:"name"`
}

type ReceiveAddressResponse struct {
	Code   int32           `json:"code"`
	Data   *ReceiveAddress `json:"data"`
	Detail string          `json:"detail"`
}

type ReceiveAddressListResponse struct {
	Code   int32             `json:"code"`
	Data   []*ReceiveAddress `json:"data"`
	Detail string            `json:"detail"`
	Total  int32             `json:"total"`
}

type ReceiveAddressRequest struct {
	Id int64 `json:"id" form:"id,optional"`
}
