// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	address "mallxx_server/member/api/internal/handler/address"
	follower "mallxx_server/member/api/internal/handler/follower"
	level "mallxx_server/member/api/internal/handler/level"
	member "mallxx_server/member/api/internal/handler/member"
	"mallxx_server/member/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: member.GetMemberInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: member.GetMemberListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/member"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: address.GetAddressListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: address.AddAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/del",
				Handler: address.DelAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/default",
				Handler: address.SetDefaultHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: address.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: address.GetAddressInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/member/address"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/level/list",
				Handler: level.GetMemverLevelListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/member/level"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/follower/list",
				Handler: follower.GetFollowerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/member/follower"),
	)
}
