// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	member "mallxx_server/member/api/internal/handler/member"
	"mallxx_server/member/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/level/list",
				Handler: member.GetMemverLevelListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: member.GetMemberInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: member.GetMemberListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/address/list",
				Handler: member.GetAddressListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/address/add",
				Handler: member.AddAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/address/del",
				Handler: member.DelAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/follower/list",
				Handler: member.GetFollowerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/member"),
	)
}
