// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mallxx_server/advertise/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: addHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: deleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: updateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: infoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/list",
				Handler: apiGetListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/list",
				Handler: adminGetListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/advertise"),
	)
}
