// Code generated by goctl. DO NOT EDIT!
// Source: advertise.proto

package server

import (
	"context"

	"mallxx_server/advertise/rpc/internal/logic"
	"mallxx_server/advertise/rpc/internal/svc"
	"mallxx_server/advertise/rpc/pb"
)

type AdvertiseServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAdvertiseServiceServer
}

func NewAdvertiseServiceServer(svcCtx *svc.ServiceContext) *AdvertiseServiceServer {
	return &AdvertiseServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AdvertiseServiceServer) AdminGetList(ctx context.Context, in *pb.AdRequest) (*pb.AdResponse, error) {
	l := logic.NewAdminGetListLogic(ctx, s.svcCtx)
	return l.AdminGetList(in)
}

func (s *AdvertiseServiceServer) ApiGetList(ctx context.Context, in *pb.AdRequest) (*pb.AdResponse, error) {
	l := logic.NewApiGetListLogic(ctx, s.svcCtx)
	return l.ApiGetList(in)
}

func (s *AdvertiseServiceServer) GetInfo(ctx context.Context, in *pb.AdOneRequest) (*pb.AdInfoResponse, error) {
	l := logic.NewGetInfoLogic(ctx, s.svcCtx)
	return l.GetInfo(in)
}

func (s *AdvertiseServiceServer) Add(ctx context.Context, in *pb.Advertise) (*pb.Response, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *AdvertiseServiceServer) Delete(ctx context.Context, in *pb.AdOneRequest) (*pb.Response, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *AdvertiseServiceServer) Update(ctx context.Context, in *pb.Advertise) (*pb.Response, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}
