// Code generated by goctl. DO NOT EDIT.
package types

type Cart struct {
	Id              int64   `json:"id,optional"`
	ProductId       int64   `json:"product_id"`
	SkuId           int64   `json:"sku_id"`
	MemberId        int64   `json:"member_id,optional"`
	Quantity        int32   `json:"quantity"`
	Price           float64 `json:"price,optional"`
	ProductPic      string  `json:"product_pic,optional"`
	ProductName     string  `json:"product_name,optional"`
	ProductSubTitle string  `json:"product_sub_title,optional"`
	SkuCode         string  `json:"sku_code,optional"`
	MemberNickname  string  `json:"member_nickname,optional"`
	CreateDate      string  `json:"create_date,optional"`
	ModifyDate      string  `json:"modify_date,optional"`
	DeleteStatus    int32   `json:"delete_status,optional"`
	CategoryId      int64   `json:"category_id,optional"`
	BrandName       string  `json:"brand_name,optional"`
	ProductSn       string  `json:"product_sn,optional"`
	ProductAttr     string  `json:"product_attr,optional"`
}

type CartAddRequest struct {
	ProductId      int64  `json:"product_id"`
	Quantity       int32  `json:"quantity"`
	MemberId       int64  `json:"member_id,optional"`
	SkuId          int64  `json:"sku_id"`
	MemberNickname string `json:"member_nicknam,optionale"`
}

type CartDelRequest struct {
	Ids []int64 `json:"ids"`
}

type CartModiyRequest struct {
	Id       int64 `json:"id"`
	Quantity int32 `json:"quantity"`
}

type CartResponse struct {
	Code   int32   `json:"code"`
	Data   []*Cart `json:"data"`
	Detail string  `json:"detail"`
}

type Response struct {
	Code   int32  `json:"code"`
	Detail string `json:"detail"`
}

type CartListRequest struct {
	MemberId int64 `json:"member_id" form:"member_id"`
}
