// Code generated by goctl. DO NOT EDIT!
// Source: cart.proto

package cartservice

import (
	"context"

	"mallxx_server/cart/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Cart             = pb.Cart
	CartAddRequest   = pb.CartAddRequest
	CartDelRequest   = pb.CartDelRequest
	CartListRequest  = pb.CartListRequest
	CartListResponse = pb.CartListResponse
	CartModiyRequest = pb.CartModiyRequest
	CartResponse     = pb.CartResponse

	CartService interface {
		AddCart(ctx context.Context, in *CartAddRequest, opts ...grpc.CallOption) (*CartResponse, error)
		DelCart(ctx context.Context, in *CartDelRequest, opts ...grpc.CallOption) (*CartResponse, error)
		ModiryCart(ctx context.Context, in *CartModiyRequest, opts ...grpc.CallOption) (*CartResponse, error)
		GetCartList(ctx context.Context, in *CartListRequest, opts ...grpc.CallOption) (*CartListResponse, error)
	}

	defaultCartService struct {
		cli zrpc.Client
	}
)

func NewCartService(cli zrpc.Client) CartService {
	return &defaultCartService{
		cli: cli,
	}
}

func (m *defaultCartService) AddCart(ctx context.Context, in *CartAddRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	client := pb.NewCartServiceClient(m.cli.Conn())
	return client.AddCart(ctx, in, opts...)
}

func (m *defaultCartService) DelCart(ctx context.Context, in *CartDelRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	client := pb.NewCartServiceClient(m.cli.Conn())
	return client.DelCart(ctx, in, opts...)
}

func (m *defaultCartService) ModiryCart(ctx context.Context, in *CartModiyRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	client := pb.NewCartServiceClient(m.cli.Conn())
	return client.ModiryCart(ctx, in, opts...)
}

func (m *defaultCartService) GetCartList(ctx context.Context, in *CartListRequest, opts ...grpc.CallOption) (*CartListResponse, error) {
	client := pb.NewCartServiceClient(m.cli.Conn())
	return client.GetCartList(ctx, in, opts...)
}
