// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code   int32  `json:"code"`
	Token  string `json:"token"`
	Host   string `json:"host"`
	Detail string `json:"detail"`
}
