// Code generated by goctl. DO NOT EDIT!
// Source: cart.proto

package server

import (
	"context"

	"mallxx_server/cart/rpc/internal/logic"
	"mallxx_server/cart/rpc/internal/svc"
	"mallxx_server/cart/rpc/pb"
)

type CartServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCartServiceServer
}

func NewCartServiceServer(svcCtx *svc.ServiceContext) *CartServiceServer {
	return &CartServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CartServiceServer) AddCart(ctx context.Context, in *pb.CartAddRequest) (*pb.CartResponse, error) {
	l := logic.NewAddCartLogic(ctx, s.svcCtx)
	return l.AddCart(in)
}

func (s *CartServiceServer) DelCart(ctx context.Context, in *pb.CartDelRequest) (*pb.CartResponse, error) {
	l := logic.NewDelCartLogic(ctx, s.svcCtx)
	return l.DelCart(in)
}

func (s *CartServiceServer) ModiryCart(ctx context.Context, in *pb.CartModiyRequest) (*pb.CartResponse, error) {
	l := logic.NewModiryCartLogic(ctx, s.svcCtx)
	return l.ModiryCart(in)
}

func (s *CartServiceServer) GetCartList(ctx context.Context, in *pb.CartListRequest) (*pb.CartListResponse, error) {
	l := logic.NewGetCartListLogic(ctx, s.svcCtx)
	return l.GetCartList(in)
}
