// Code generated by goctl. DO NOT EDIT.
package types

type ListRequest struct {
	PageNum  int32  `json:"page_num,optional" form:"page_num,optional"`
	PageSize int32  `json:"page_size,optional" form:"page_size,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
	Pid      int64  `json:"pid,optional" form:"pid,optional"`
}

type Response struct {
	Code   int32  `json:"code,optional"`
	Detail string `json:"detail,optional"`
}

type IdRequest struct {
	Id int64 `json:"id" form:"id"` 
}

type Brand struct {
	Id                  int64  `json:"id,optional"`
	FirstLetter         string `json:"first_letter,optional"`
	Sort                int32  `json:"sort,optional"`
	FactoryStatus       int32  `json:"factory_status,optional"`
	ShowStatus          int32  `json:"show_status,optional"`
	ProductCount        int64  `json:"product_count,optional"`
	ProductCommentCount int64  `json:"product_comment_count,optional"`
	Logo                string `json:"logo,optional"`
	BigPic              string `json:"big_pic,optional"`
	BrandStory          string `json:"brand_story,optional"`
	Name                string `json:"name,optional"`
	Url                 string `json:"url,optional"`
}

type BrandRequest struct {
	PageNum  int32  `json:"page_num,optional" form:"page_num,optional"`
	PageSize int32  `json:"page_size,optional" form:"page_size,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
	Id       int64  `json:"id,optional" form:"id,optional"`
}

type BrandStatusRequest struct {
	Id     int64 `json:"id,optional"`
	Status int32 `json:"status,optional"`
}

type BrandListResponse struct {
	Code   int32    `json:"code,optional"`
	Data   []*Brand `json:"data,optional"`
	Detail string   `json:"detail"`
	Total  int64    `json:"total"`
}

type BrandOneResponse struct {
	Code   int32  `json:"code"`
	Data   *Brand `json:"data"`
	Detail string `json:"detail"`
}

type CategoryAttribute struct {
	Id             int64  `json:"id,optional"`
	Name           string `json:"name,optional"`
	AttributeCount int32  `json:"attribute_count,optional"`
	ParamCount     int32  `json:"param_count,optional"`
}

type CategoryAttributeListResponse struct {
	Code   int32                `json:"code"`
	Data   []*CategoryAttribute `json:"data"`
	Total  int64                `json:"total"`
	Detail string               `json:"detail"`
}

type CategoryAttributeInfoResponse struct {
	Code   int32              `json:"code"`
	Data   *CategoryAttribute `json:"data"`
	Detail string             `json:"detail"`
}

type CategoryAttrAndProductAttr struct {
	CategoryAttr *CategoryAttribute  `json:"category_attr,optional"`
	Children     []*ProductAttribute `json:"children,optional"`
}

type CategoryAttrAndProductAttrListResponse struct {
	Code   int32                         `json:"code"`
	Data   []*CategoryAttrAndProductAttr `json:"data"`
	Detail string                        `json:"detail"`
}

type Category struct {
	Id                  int64   `json:"id,optional"`
	ParentId            int64   `json:"parent_id,optional"`
	Level               int32   `json:"level,optional"`
	ProductCount        int32   `json:"product_count,optional"`
	ProductUnit         string  `json:"product_unit,optional"`
	NavStatus           int32   `json:"nav_status,optional"`
	ShowStatus          int32   `json:"show_status,optional"`
	Sort                int32   `json:"sort,optional"`
	Icon                string  `json:"icon,optional"`
	Name                string  `json:"name,optional"`
	Keywords            string  `json:"keywords,optional"`
	Description         string  `json:"description,optional"`
	ProductAttributeIds []int64 `json:"product_attribute_ids,optional"`
}

type CategoryResponse struct {
	Code   int32       `json:"code"`
	Data   []*Category `json:"data"`
	Detail string      `json:"detail"`
	Total  int64       `json:"total"`
}

type CategoryInfoResponse struct {
	Code   int32     `json:"code"`
	Data   *Category `json:"data"`
	Detail string    `json:"detail"`
}

type CategoryChangeStatus struct {
	Id     int64 `json:"id"`
	Status int32 `json:"status"`
}

type MemberPrice struct {
	Id              int64   `json:"id,optional"`
	ProductId       int64   `json:"product_id,optional"`
	MemberLevelId   int64   `json:"member_level_id,optional"`
	MemberPrice     float32 `json:"member_price,optional"`
	MemberLevelName string  `json:"member_level_name,optional"`
}

type ProductAttributeValue struct {
	Id                 int64  `json:"id,optional"`
	ProductId          int64  `json:"product_id,optional"`
	ProductAttributeId int64  `json:"product_attribute_id,optional"`
	Value              string `json:"value,optional"`
}

type ProductAttribute struct {
	Id                  int64  `json:"id,optional"`
	CategoryAttributeId int64  `json:"category_attribute_id,optional"`
	SelectType          int32  `json:"select_type,optional"`
	InputType           int32  `json:"input_type,optional"`
	Sort                int32  `json:"sort,optional"`
	FilterType          int32  `json:"filter_type,optional"`
	SearchType          int32  `json:"search_type,optional"`
	RelatedStatus       int32  `json:"related_status,optional"`
	HandAddStatus       int32  `json:"hand_add_status,optional"`
	Type                int32  `json:"type,optional"`
	Name                string `json:"name,optional"`
	InputList           string `json:"input_list,optional"`
}

type ProductAttributeListResponse struct {
	Code   int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Data   []*ProductAttribute `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
	Detail string              `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail"`
	Total  int64               `protobuf:"varint,5,opt,name=total,proto3" json:"total"`
}

type ProductAttributeInfoResponse struct {
	Code   int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Data   *ProductAttribute `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
	Detail string            `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail"`
}

type AttrRequest struct {
	PageNum  int32  `json:"page_num,optional" form:"page_num,optional"`
	PageSize int32  `json:"page_size,optional" form:"page_size,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
	Cid      int64  `json:"cid,optional" form:"cid,optional"`
	Type     int32  `json:"type,optional" form:"type,optional"`
	Language string `json:"language,optional" form:"language,optional"`
}

type ProductFullReduction struct {
	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,optional"`
	ProductId   int64   `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,optional"`
	FullPrice   float32 `protobuf:"fixed32,3,opt,name=full_price,json=fullPrice,proto3" json:"full_price,optional"`
	ReducePrice float32 `protobuf:"fixed32,4,opt,name=reduce_price,json=reducePrice,proto3" json:"reduce_price,optional"`
}

type ProductLadder struct {
	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,optional"`
	ProductId int64   `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,optional"`
	Count     int32   `protobuf:"varint,3,opt,name=count,proto3" json:"count,optional"`
	Discount  float32 `protobuf:"fixed32,4,opt,name=discount,proto3" json:"discount,optional"`
	Price     float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,optional"`
}

type ProductRecommend struct {
	Id          int64  `json:"id,optional"`
	ProductId   int64  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,optional"`
	ProductName string `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,optional"`
	Sort        int32  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,optional"`
}

type RecommendRequest struct {
	ProductIds []int64 `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,optional"`
}

type RecommendSetSortRequest struct {
	Id   int64 `json:"id,optional"`
	Sort int32 `protobuf:"varint,2,opt,name=sort,proto3" json:"sort,optional"`
}

type RecommendListResponse struct {
	Code   int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Data   []*ProductRecommend `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
	Total  int64               `protobuf:"varint,3,opt,name=total,proto3" json:"total"`
	Detail string              `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail"`
}

type Product struct {
	Id                         int64                    `json:"id,optional"`
	BrandId                    int64                    `json:"brand_id,optional"`
	ProductCategoryId          int64                    `json:"product_category_id,optional"`
	FeightTemplateId           int64                    `json:"feight_template_id,optional"`
	ProductAttributeCategoryId int64                    `json:"product_attribute_category_id,optional"`
	ProductSn                  string                   `json:"product_sn,optional"`
	DeleteStatus               int32                    `json:"delete_status,optional"`
	PublishStatus              int32                    `json:"publish_status,optional"`
	NewStatus                  int32                    `protobuf:"varint,9,opt,name=new_status,json=newStatus,proto3" json:"new_status"`
	RecommendStatus            int32                    `protobuf:"varint,10,opt,name=recommend_status,json=recommendStatus,proto3" json:"recommend_status,optional"`
	VerifyStatus               int32                    `protobuf:"varint,11,opt,name=verify_status,json=verifyStatus,proto3" json:"verify_status,optional"`
	Sort                       int32                    `protobuf:"varint,12,opt,name=sort,proto3" json:"sort,optional"`
	Sale                       int64                    `protobuf:"varint,13,opt,name=sale,proto3" json:"sale,optional"`
	Price                      float64                  `protobuf:"fixed64,14,opt,name=price,proto3" json:"price,optional"`
	PromotionPrice             float64                  `protobuf:"fixed64,15,opt,name=promotion_price,json=promotionPrice,proto3" json:"promotion_price,optional"`
	GiftGrowth                 int64                    `protobuf:"varint,16,opt,name=gift_growth,json=giftGrowth,proto3" json:"gift_growth,optional"`
	GiftPoint                  int64                    `protobuf:"varint,17,opt,name=gift_point,json=giftPoint,proto3" json:"gift_point,optional"`
	UsePointLimit              int64                    `protobuf:"varint,18,opt,name=use_point_limit,json=usePointLimit,proto3" json:"use_point_limit,optional"`
	OriginalPrice              float64                  `protobuf:"fixed64,19,opt,name=original_price,json=originalPrice,proto3" json:"original_price,optional"`
	Stock                      int64                    `protobuf:"varint,20,opt,name=stock,proto3" json:"stock,optional"`
	LowStock                   int64                    `protobuf:"varint,21,opt,name=low_stock,json=lowStock,proto3" json:"low_stock,optional"`
	Unit                       string                   `protobuf:"bytes,22,opt,name=unit,proto3" json:"unit,optional"`
	Weight                     float64                  `protobuf:"fixed64,23,opt,name=weight,proto3" json:"weight,optional"`
	PreviewStatus              int32                    `protobuf:"varint,24,opt,name=preview_status,json=previewStatus,proto3" json:"preview_status,optional"`
	ServiceIds                 string                   `protobuf:"bytes,25,opt,name=service_ids,json=serviceIds,proto3" json:"service_ids,optional"`
	Pic                        string                   `protobuf:"bytes,26,opt,name=pic,proto3" json:"pic,optional"`
	AlbumPics                  string                   `protobuf:"bytes,27,opt,name=album_pics,json=albumPics,proto3" json:"album_pics,optional"`
	PromotionStartTime         string                   `protobuf:"bytes,28,opt,name=promotion_start_time,json=promotionStartTime,proto3" json:"promotion_start_time,optional"`
	PromotionEndTime           string                   `protobuf:"bytes,29,opt,name=promotion_end_time,json=promotionEndTime,proto3" json:"promotion_end_time,optional"`
	PromotionPerLimit          int32                    `protobuf:"varint,30,opt,name=promotion_per_limit,json=promotionPerLimit,proto3" json:"promotion_per_limit,optional"`
	PromotionType              int32                    `protobuf:"varint,31,opt,name=promotion_type,json=promotionType,proto3" json:"promotion_type,optional"`
	Name                       string                   `protobuf:"bytes,32,opt,name=name,proto3" json:"name,optional"`
	SubTitle                   string                   `protobuf:"bytes,33,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,optional"`
	Description                string                   `protobuf:"bytes,34,opt,name=description,proto3" json:"description,optional"`
	Keywords                   string                   `protobuf:"bytes,35,opt,name=keywords,proto3" json:"keywords,optional"`
	Note                       string                   `protobuf:"bytes,36,opt,name=note,proto3" json:"note,optional"`
	DetailTitle                string                   `protobuf:"bytes,37,opt,name=detail_title,json=detailTitle,proto3" json:"detail_title,optional"`
	DetailDesc                 string                   `protobuf:"bytes,38,opt,name=detail_desc,json=detailDesc,proto3" json:"detail_desc,optional"`
	DetailHtml                 string                   `protobuf:"bytes,39,opt,name=detail_html,json=detailHtml,proto3" json:"detail_html,optional"`
	DetailMobileHtml           string                   `protobuf:"bytes,40,opt,name=detail_mobile_html,json=detailMobileHtml,proto3" json:"detail_mobile_html,optional"`
	ProductCategoryName        string                   `protobuf:"bytes,41,opt,name=product_category_name,json=productCategoryName,proto3" json:"product_category_name,optional"`
	BrandName                  string                   `protobuf:"bytes,42,opt,name=brand_name,json=brandName,proto3" json:"brand_name,optional"`
	SkuStock                   []*SkuStock              `protobuf:"bytes,43,rep,name=sku_stock,json=skuStock,proto3" json:"sku_stock,optional"`
	ProductLadder              []*ProductLadder         `protobuf:"bytes,44,rep,name=product_ladder,json=productLadder,proto3" json:"product_ladder,optional"`
	ProductFullReduction       []*ProductFullReduction  `protobuf:"bytes,45,rep,name=product_full_reduction,json=productFullReduction,proto3" json:"product_full_reduction,optional"`
	ProductAttrValue           []*ProductAttributeValue `protobuf:"bytes,46,rep,name=product_attr_value,json=productAttrValue,proto3" json:"product_attr_value,optional"`
	MemberPrice                []*MemberPrice           `protobuf:"bytes,47,rep,name=member_price,json=memberPrice,proto3" json:"member_price,optional"`
	ProductAttribute           []*ProductAttribute      `protobuf:"bytes,48,rep,name=product_attribute,json=productAttribute,proto3" json:"product_attribute,optional"`
	CommentNumber              int64                    `protobuf:"varint,49,opt,name=comment_number,json=commentNumber,proto3" json:"comment_number,optional"`
	Parameters                 []*ProductParameters     `protobuf:"bytes,50,rep,name=parameters,proto3" json:"parameters,optional"`
}

type ProductInfoRequest struct {
	Id int64 `json:"id,optional" form:"id"`
}

type ProductListRequest struct {
	PageNum         int32  `json:"page_num,optional" from:"page_num,optional"`
	PageSize        int32  `json:"page_size,optional" from:"page_size,optional"`
	Name            string `json:"name,optional" from:"name,optional"`
	Sn              string `json:"sn,optional" from:"sn,optional"`
	CategoryId      int64  `json:"category_id,optional" from:"category_id,optional"`
	BrandId         int64  `json:"brand_id,optional" from:"brand_id,optional"` 
	PublishStatus   int32  `json:"publish_status,optional" from:"publish_status,optional"`
	VerifyStatus    int32  `json:"verify_status,optional" from:"verify_status,optional"`
	RecommendStatus int32  `json:"recommend_status,optional" from:"recommend_status,optional"`
	NewStatus       int32  `json:"new_status,optional" from:"new_status,optional"`
}

type ProductChangeStatusRequest struct {
	Id     int64 `json:"id"`
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status"`
}

type ProductInfoResponse struct {
	Code   int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Data   *Product `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
	Detail string   `protobuf:"bytes,8,opt,name=detail,proto3" json:"detail"`
}

type ProductListRespone struct {
	Code   int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Data   []*Product `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
	Detail string     `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail"`
	Total  int64      `protobuf:"varint,4,opt,name=total,proto3" json:"total"`
}

type ProductApiRequest struct {
	CategoryIds []int64 `protobuf:"varint,1,rep,packed,name=category_ids,json=categoryIds,proto3" json:"category_ids,optional"`
	Sort        string  `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,optional"`
	BrandIds    []int64 `protobuf:"varint,3,rep,packed,name=brand_ids,json=brandIds,proto3" json:"brand_ids,optional"`
	MinPrice    float64 `protobuf:"fixed64,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,optional"`
	MixPrice    float64 `protobuf:"fixed64,5,opt,name=mix_price,json=mixPrice,proto3" json:"mix_price,optional"`
	PageNum     int32   `protobuf:"varint,6,opt,name=page_num,json=pageNum,proto3" json:"page_num,optional"`
	PageSize    int32   `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,optional"`
}

type ProductParameters struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
}

type SkuStock struct {
	Id             int64   `json:"id,optional"`
	ProductId      int64   `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,optional"`
	SkuCode        string  `protobuf:"bytes,3,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,optional"`
	Price          float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,optional"`
	Stock          int32   `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,optional"`
	LowStock       int32   `protobuf:"varint,6,opt,name=low_stock,json=lowStock,proto3" json:"low_stock,optional"`
	SpData         string  `protobuf:"bytes,7,opt,name=sp_data,json=spData,proto3" json:"sp_data,optional"`
	Pic            string  `protobuf:"bytes,8,opt,name=pic,proto3" json:"pic,optional"`
	Sale           int32   `protobuf:"varint,9,opt,name=sale,proto3" json:"sale,optional"`
	LockStock      int32   `json:"lock_stock,optional"`
}

type SkuStockListResponse struct {
	Code   int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Data   []*SkuStock `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
	Detail string      `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail"`
}

type SkuStockRequest struct {
	ProductId int64  `json:"product_id,optional"`
	Keyword   string `json:"keyword,optional"`
}

type SkuStockListRequest struct {
	List []*SkuStock `json:"list,optional"`
}

type EmptyRequest struct {
}
