// Code generated by goctl. DO NOT EDIT.
package types

type ListRequest struct {
	PageNum  int32  `json:"page_num,optional" form:"page_num,optional"`
	PageSize int32  `json:"page_size,optional" form:"page_size,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
	Pid      int64  `json:"pid,optional" form:"pid,optional"`
}

type Response struct {
	Code   int32  `json:"code,optional"`
	Detail string `json:"detail,optional"`
}

type IdRequest struct {
	Id int64 `json:"id" form:"id"` 
}

type Brand struct {
	Id                  int64  `json:"id,optional"`
	FirstLetter         string `json:"first_letter,optional"`
	Sort                int32  `json:"sort,optional"`
	FactoryStatus       int32  `json:"factory_status,optional"`
	ShowStatus          int32  `json:"show_status,optional"`
	ProductCount        int64  `json:"product_count,optional"`
	ProductCommentCount int64  `json:"product_comment_count,optional"`
	Logo                string `json:"logo,optional"`
	BigPic              string `json:"big_pic,optional"`
	BrandStory          string `json:"brand_story,optional"`
	Name                string `json:"name,optional"`
	Url                 string `json:"url,optional"`
}

type BrandRequest struct {
	PageNum  int32  `json:"page_num,optional" form:"page_num,optional"`
	PageSize int32  `json:"page_size,optional" form:"page_size,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
	Id       int64  `json:"id,optional" form:"id,optional"`
}

type BrandStatusRequest struct {
	Id     int64 `json:"id,optional"`
	Status int32 `json:"status,optional"`
}

type BrandListResponse struct {
	Code   int32    `json:"code,optional"`
	Data   []*Brand `json:"data,optional"`
	Detail string   `json:"detail"`
	Total  int64    `json:"total"`
}

type BrandOneResponse struct {
	Code   int32  `json:"code"`
	Data   *Brand `json:"data"`
	Detail string `json:"detail"`
}

type CategoryAttribute struct {
	Id             int64  `json:"id,optional"`
	Name           string `json:"name,optional"`
	AttributeCount int32  `json:"attribute_count,optional"`
	ParamCount     int32  `json:"param_count,optional"`
}

type CategoryAttributeListResponse struct {
	Code   int32                `json:"code"`
	Data   []*CategoryAttribute `json:"data"`
	Total  int64                `json:"total"`
	Detail string               `json:"detail"`
}

type CategoryAttributeInfoResponse struct {
	Code   int32              `json:"code"`
	Data   *CategoryAttribute `json:"data"`
	Detail string             `json:"detail"`
}

type CategoryAttrAndProductAttr struct {
	CategoryAttr *CategoryAttribute  `json:"category_attr,optional"`
	Children     []*ProductAttribute `json:"children,optional"`
}

type CategoryAttrAndProductAttrListResponse struct {
	Code   int32                         `json:"code"`
	Data   []*CategoryAttrAndProductAttr `json:"data"`
	Detail string                        `json:"detail"`
}

type Category struct {
	Id                  int64   `json:"id,optional"`
	ParentId            int64   `json:"parent_id,optional"`
	Level               int32   `json:"level,optional"`
	ProductCount        int32   `json:"product_count,optional"`
	ProductUnit         string  `json:"product_unit,optional"`
	NavStatus           int32   `json:"nav_status,optional"`
	ShowStatus          int32   `json:"show_status,optional"`
	Sort                int32   `json:"sort,optional"`
	Icon                string  `json:"icon,optional"`
	Name                string  `json:"name,optional"`
	Keywords            string  `json:"keywords,optional"`
	Description         string  `json:"description,optional"`
	ProductAttributeIds []int64 `json:"product_attribute_ids,optional"`
}

type CategoryResponse struct {
	Code   int32       `json:"code"`
	Data   []*Category `json:"data"`
	Detail string      `json:"detail"`
	Total  int64       `json:"total"`
}

type CategoryInfoResponse struct {
	Code   int32     `json:"code"`
	Data   *Category `json:"data"`
	Detail string    `json:"detail"`
}

type CategoryChangeStatus struct {
	Id     int64 `json:"id"`
	Status int32 `json:"status"`
}

type MemberPrice struct {
	Id              int64   `json:"id,optional"`
	ProductId       int64   `json:"product_id,optional"`
	MemberLevelId   int64   `json:"member_level_id,optional"`
	MemberPrice     float32 `json:"member_price,optional"`
	MemberLevelName string  `json:"member_level_name,optional"`
}

type ProductAttributeValue struct {
	Id                 int64  `json:"id,optional"`
	ProductId          int64  `json:"product_id,optional"`
	ProductAttributeId int64  `json:"product_attribute_id,optional"`
	Value              string `json:"value,optional"`
}

type ProductAttribute struct {
	Id                  int64  `json:"id,optional"`
	CategoryAttributeId int64  `json:"category_attribute_id,optional"`
	SelectType          int32  `json:"select_type,optional"`
	InputType           int32  `json:"input_type,optional"`
	Sort                int32  `json:"sort,optional"`
	FilterType          int32  `json:"filter_type,optional"`
	SearchType          int32  `json:"search_type,optional"`
	RelatedStatus       int32  `json:"related_status,optional"`
	HandAddStatus       int32  `json:"hand_add_status,optional"`
	Type                int32  `json:"type,optional"`
	Name                string `json:"name,optional"`
	InputList           string `json:"input_list,optional"`
}

type ProductAttributeListResponse struct {
	Code   int32               `json:"code"`
	Data   []*ProductAttribute `json:"data"`
	Detail string              `json:"detail"`
	Total  int64               `json:"total"`
}

type ProductAttributeInfoResponse struct {
	Code   int32             `json:"code"`
	Data   *ProductAttribute `json:"data"`
	Detail string            `json:"detail"`
}

type AttrRequest struct {
	PageNum  int32  `json:"page_num,optional" form:"page_num,optional"`
	PageSize int32  `json:"page_size,optional" form:"page_size,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
	Cid      int64  `json:"cid,optional" form:"cid,optional"`
	Type     int32  `json:"type,optional" form:"type,optional"`
	Language string `json:"language,optional" form:"language,optional"`
}

type ProductFullReduction struct {
	Id          int64   `json:"id,optional"`
	ProductId   int64   `json:"product_id,optional"`
	FullPrice   float32 `json:"full_price,optional"`
	ReducePrice float32 `json:"reduce_price,optional"`
}

type ProductLadder struct {
	Id        int64   `json:"id,optional"`
	ProductId int64   `json:"product_id,optional"`
	Count     int32   `json:"count,optional"`
	Discount  float32 `json:"discount,optional"`
	Price     float32 `json:"price,optional"`
}

type ProductRecommend struct {
	Id          int64  `json:"id,optional"`
	ProductId   int64  `json:"product_id,optional"`
	ProductName string `json:"product_name,optional"`
	Sort        int32  `json:"sort,optional"`
}

type RecommendRequest struct {
	ProductIds []int64 `json:"product_ids,optional"`
}

type RecommendSetSortRequest struct {
	Id   int64 `json:"id,optional"`
	Sort int32 `json:"sort,optional"`
}

type RecommendListResponse struct {
	Code   int32               `json:"code"`
	Data   []*ProductRecommend `json:"data"`
	Total  int64               `json:"total"`
	Detail string              `json:"detail"`
}

type Product struct {
	Id                         int64                    `json:"id,optional"`
	BrandId                    int64                    `json:"brand_id,optional"`
	ProductCategoryId          int64                    `json:"product_category_id,optional"`
	FeightTemplateId           int64                    `json:"feight_template_id,optional"`
	ProductAttributeCategoryId int64                    `json:"product_attribute_category_id,optional"`
	ProductSn                  string                   `json:"product_sn,optional"`
	DeleteStatus               int32                    `json:"delete_status,optional"`
	PublishStatus              int32                    `json:"publish_status,optional"`
	NewStatus                  int32                    `json:"new_status"`
	RecommendStatus            int32                    `json:"recommend_status,optional"`
	VerifyStatus               int32                    `json:"verify_status,optional"`
	Sort                       int32                    `json:"sort,optional"`
	Sale                       int64                    `json:"sale,optional"`
	Price                      float64                  `json:"price,optional"`
	PromotionPrice             float64                  `json:"promotion_price,optional"`
	GiftGrowth                 int64                    `json:"gift_growth,optional"`
	GiftPoint                  int64                    `json:"gift_point,optional"`
	UsePointLimit              int64                    `json:"use_point_limit,optional"`
	OriginalPrice              float64                  `json:"original_price,optional"`
	Stock                      int64                    `json:"stock,optional"`
	LowStock                   int64                    `json:"low_stock,optional"`
	Unit                       string                   `json:"unit,optional"`
	Weight                     float64                  `json:"weight,optional"`
	PreviewStatus              int32                    `json:"preview_status,optional"`
	ServiceIds                 string                   `json:"service_ids,optional"`
	Pic                        string                   `json:"pic,optional"`
	AlbumPics                  string                   `json:"album_pics,optional"`
	PromotionStartTime         string                   `json:"promotion_start_time,optional"`
	PromotionEndTime           string                   `json:"promotion_end_time,optional"`
	PromotionPerLimit          int32                    `json:"promotion_per_limit,optional"`
	PromotionType              int32                    `json:"promotion_type,optional"`
	Name                       string                   `json:"name,optional"`
	SubTitle                   string                   `json:"sub_title,optional"`
	Description                string                   `json:"description,optional"`
	Keywords                   string                   `json:"keywords,optional"`
	Note                       string                   `json:"note,optional"`
	DetailTitle                string                   `json:"detail_title,optional"`
	DetailDesc                 string                   `json:"detail_desc,optional"`
	DetailHtml                 string                   `json:"detail_html,optional"`
	DetailMobileHtml           string                   `json:"detail_mobile_html,optional"`
	ProductCategoryName        string                   `json:"product_category_name,optional"`
	BrandName                  string                   `json:"brand_name,optional"`
	SkuStock                   []*SkuStock              `json:"sku_stock,optional"`
	ProductLadder              []*ProductLadder         `json:"product_ladder,optional"`
	ProductFullReduction       []*ProductFullReduction  `json:"product_full_reduction,optional"`
	ProductAttrValue           []*ProductAttributeValue `json:"product_attr_value,optional"`
	MemberPrice                []*MemberPrice           `json:"member_price,optional"`
	ProductAttribute           []*ProductAttribute      `json:"product_attribute,optional"`
	CommentNumber              int64                    `json:"comment_number,optional"`
	Parameters                 []*ProductParameters     `json:"parameters,optional"`
}

type ProductInfoRequest struct {
	Id int64 `json:"id,optional" form:"id"`
}

type ProductListRequest struct {
	PageNum         int32  `json:"page_num,optional" form:"page_num,optional"`
	PageSize        int32  `json:"page_size,optional" form:"page_size,optional"`
	Name            string `json:"name,optional" form:"name,optional"`
	Sn              string `json:"sn,optional" form:"sn,optional"`
	CategoryId      int64  `json:"category_id,optional" form:"category_id,optional"`
	BrandId         int64  `json:"brand_id,optional" form:"brand_id,optional"` 
	PublishStatus   int32  `json:"publish_status,optional" form:"publish_status,optional"`
	VerifyStatus    int32  `json:"verify_status,optional" form:"verify_status,optional"`
	RecommendStatus int32  `json:"recommend_status,optional" form:"recommend_status,optional"`
	NewStatus       int32  `json:"new_status,optional" form:"new_status,optional"`
}

type ProductChangeStatusRequest struct {
	Id     int64 `json:"id"`
	Status int32 `json:"status"`
}

type ProductInfoResponse struct {
	Code   int32    `json:"code"`
	Data   *Product `json:"data"`
	Detail string   `json:"detail"`
}

type ProductListRespone struct {
	Code   int32      `json:"code"`
	Data   []*Product `json:"data"`
	Detail string     `json:"detail"`
	Total  int64      `json:"total"`
}

type ProductApiRequest struct {
	CategoryIds []int64 `json:"category_ids,optional"`
	Sort        string  `json:"sort,optional"`
	BrandIds    []int64 `json:"brand_ids,optional"`
	MinPrice    float64 `json:"min_price,optional"`
	MixPrice    float64 `json:"mix_price,optional"`
	PageNum     int32   `json:"page_num,optional"`
	PageSize    int32   `json:"page_size,optional"`
}

type ProductParameters struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SkuStock struct {
	Id             int64   `json:"id,optional"`
	ProductId      int64   `json:"product_id,optional"`
	SkuCode        string  `json:"sku_code,optional"`
	Price          float32 `json:"price,optional"`
	Stock          int32   `json:"stock,optional"`
	LowStock       int32   `json:"low_stock,optional"`
	SpData         string  `json:"sp_data,optional"`
	Pic            string  `json:"pic,optional"`
	Sale           int32   `json:"sale,optional"`
	LockStock      int32   `json:"lock_stock,optional"`
}

type SkuStockListResponse struct {
	Code   int32       `json:"code"`
	Data   []*SkuStock `json:"data"`
	Detail string      `json:"detail"`
}

type SkuStockRequest struct {
	ProductId int64  `json:"product_id,optional" form:"product_id,optional"`
	Keyword   string `json:"keyword,optional" form:"keyword,optional"`
}

type SkuStockListRequest struct {
	List []*SkuStock `json:"list,optional"`
}

type EmptyRequest struct {
}
