// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package orderservice

import (
	"context"

	"mallxx_server/order/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CompanyAddress        = pb.CompanyAddress
	GenerateOrderRequest  = pb.GenerateOrderRequest
	GenerateOrderResponse = pb.GenerateOrderResponse
	Order                 = pb.Order
	OrderFirm             = pb.OrderFirm
	OrderFirmRequest      = pb.OrderFirmRequest
	OrderFirmResponse     = pb.OrderFirmResponse
	OrderInfoRequest      = pb.OrderInfoRequest
	OrderInfoRsponse      = pb.OrderInfoRsponse
	OrderListRequest      = pb.OrderListRequest
	OrderListResponse     = pb.OrderListResponse
	OrderMemberRequest    = pb.OrderMemberRequest
	OrderOperateHistory   = pb.OrderOperateHistory
	OrderProduct          = pb.OrderProduct
	OrderResponse         = pb.OrderResponse
	OrderReturnApply      = pb.OrderReturnApply
	OrderReturnReason     = pb.OrderReturnReason

	Orderservice interface {
		OrderFrim(ctx context.Context, in *OrderFirmRequest, opts ...grpc.CallOption) (*OrderFirmResponse, error)
		OrderGenerate(ctx context.Context, in *GenerateOrderRequest, opts ...grpc.CallOption) (*GenerateOrderResponse, error)
		OrderMemberList(ctx context.Context, in *OrderMemberRequest, opts ...grpc.CallOption) (*OrderListResponse, error)
		OrderInfo(ctx context.Context, in *OrderInfoRequest, opts ...grpc.CallOption) (*OrderInfoRsponse, error)
		OrderCancel(ctx context.Context, in *OrderInfoRequest, opts ...grpc.CallOption) (*OrderResponse, error)
		OrderDelete(ctx context.Context, in *OrderInfoRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	}

	defaultOrderservice struct {
		cli zrpc.Client
	}
)

func NewOrderservice(cli zrpc.Client) Orderservice {
	return &defaultOrderservice{
		cli: cli,
	}
}

func (m *defaultOrderservice) OrderFrim(ctx context.Context, in *OrderFirmRequest, opts ...grpc.CallOption) (*OrderFirmResponse, error) {
	client := pb.NewOrderserviceClient(m.cli.Conn())
	return client.OrderFrim(ctx, in, opts...)
}

func (m *defaultOrderservice) OrderGenerate(ctx context.Context, in *GenerateOrderRequest, opts ...grpc.CallOption) (*GenerateOrderResponse, error) {
	client := pb.NewOrderserviceClient(m.cli.Conn())
	return client.OrderGenerate(ctx, in, opts...)
}

func (m *defaultOrderservice) OrderMemberList(ctx context.Context, in *OrderMemberRequest, opts ...grpc.CallOption) (*OrderListResponse, error) {
	client := pb.NewOrderserviceClient(m.cli.Conn())
	return client.OrderMemberList(ctx, in, opts...)
}

func (m *defaultOrderservice) OrderInfo(ctx context.Context, in *OrderInfoRequest, opts ...grpc.CallOption) (*OrderInfoRsponse, error) {
	client := pb.NewOrderserviceClient(m.cli.Conn())
	return client.OrderInfo(ctx, in, opts...)
}

func (m *defaultOrderservice) OrderCancel(ctx context.Context, in *OrderInfoRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	client := pb.NewOrderserviceClient(m.cli.Conn())
	return client.OrderCancel(ctx, in, opts...)
}

func (m *defaultOrderservice) OrderDelete(ctx context.Context, in *OrderInfoRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	client := pb.NewOrderserviceClient(m.cli.Conn())
	return client.OrderDelete(ctx, in, opts...)
}
