Name: product.rpc
ListenOn: 127.0.0.1:8082
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc


Redis:
  Host: 127.0.0.1:6379
  Type: node
  Pass:

Mysql:
  DataSource: root:luxixi1990@tcp(127.0.0.1:3306)/mallxx_product?charset=utf8mb4&interpolateParams=true
