// Code generated by goctl. DO NOT EDIT.
package types

type AdminInfo struct {
	Roles        string `json:"roles"`
	Introduction string `json:"introduction"`
	Avatar       string `json:"avatar"`
	Name         string `json:"name,omitempty"`
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	Password     string `json:"password"`
	Token        string `json:"token" xorm:"-"`
}

type AdminInfoResponse struct {
	Code   int32      `json:"code"`
	Data   *AdminInfo `json:"data"`
	Detail string     `json:"detail"`
}

type AdmminLoginReqeust struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
