// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	order "mallxx_server/order/api/internal/handler/order"
	"mallxx_server/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/frim",
				Handler: order.OrderFrimHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/generate",
				Handler: order.OrderGenerateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/member/list",
				Handler: order.OrderMemberListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/info",
				Handler: order.OrderInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cancel",
				Handler: order.OrderCancelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: order.OrderDeleteHandler(serverCtx),
			},
		},
		rest.WithPrefix("/order"),
	)
}
