// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	cart "mallxx_server/cart/api/internal/handler/cart"
	"mallxx_server/cart/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: cart.AddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: cart.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/modify",
				Handler: cart.ModifyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: cart.GetListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cart"),
	)
}
