// Code generated by goctl. DO NOT EDIT!
// Source: admin.proto

package server

import (
	"context"

	"mallxx_server/admin/rpc/internal/logic"
	"mallxx_server/admin/rpc/internal/svc"
	"mallxx_server/admin/rpc/pb"
)

type AdminServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAdminServiceServer
}

func NewAdminServiceServer(svcCtx *svc.ServiceContext) *AdminServiceServer {
	return &AdminServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServiceServer) Login(ctx context.Context, in *pb.AdminInfo) (*pb.AdminInfoResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AdminServiceServer) GetInfo(ctx context.Context, in *pb.AdminInfo) (*pb.AdminInfoResponse, error) {
	l := logic.NewGetInfoLogic(ctx, s.svcCtx)
	return l.GetInfo(in)
}

func (s *AdminServiceServer) Create(ctx context.Context, in *pb.AdminInfo) (*pb.AdminInfoResponse, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *AdminServiceServer) Update(ctx context.Context, in *pb.AdminInfo) (*pb.Response, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *AdminServiceServer) Delete(ctx context.Context, in *pb.AdminInfo) (*pb.Response, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *AdminServiceServer) VerifyToken(ctx context.Context, in *pb.AdminTokenRequest) (*pb.Response, error) {
	l := logic.NewVerifyTokenLogic(ctx, s.svcCtx)
	return l.VerifyToken(in)
}

func (s *AdminServiceServer) CleanToken(ctx context.Context, in *pb.AdminTokenRequest) (*pb.Response, error) {
	l := logic.NewCleanTokenLogic(ctx, s.svcCtx)
	return l.CleanToken(in)
}
